### ISSUE TITLE
还有没有其他的机器人推荐  这玩意太硬核了吧。。

### ISSUE THREAD

**Issue by lonpat** [sfyc23/EverydayWechat#104]
![QQ图片20190614193151](https://user-images.githubusercontent.com/50951908/59506662-667d9900-8edb-11e9-9caf-4b869347ef20.png)

**Comment by sfyc23** [comment]
分手神器。

**Comment by JasonVenn** [comment]
半夜笑出声

**Comment by G-BlueSummer** [comment]
😂

**Comment by yaochuanting** [comment]
hhhhh笑出猪叫

**Comment by sfyc23** [comment]
新添加了一个机器人『[一个AI](http://www.yige.ai)』，我感觉还算不错了，关键好多还可以自定义设置。

**Comment by G-BlueSummer** [comment]
自己做一个咧 https://github.com/warmheartli/ChatBotCourse

**Comment by sfyc23** [comment]
> 自己做一个咧 https://github.com/warmheartli/ChatBotCourse

@G-BlueSummer 这些从训练到能达到使用，很容易把人逼退的。我之后再把手动做机器人的一些相关资源也放在 readme 中吧。

**Comment by tianly123** [comment]
哈哈哈哈哈哈哈，突然不想玩这个了
