### ISSUE TITLE
时间应从第一天开始哦

### ISSUE THREAD

**Issue by yz-xlame** [sfyc23/EverydayWechat#106]
我如果把时间设置成今天，那么会出现第0天，那是不是我设置成明天什么的还有负数的？

**Comment by sfyc23** [comment]
时间应该 +1 的。设置成明天，为什么要这么干呢。。。。

**Comment by yz-xlame** [comment]
@sfyc23 就不准今天恋爱今天发的吗?恋爱第一天不算?

**Comment by sfyc23** [comment]
> @sfyc23 就不准今天恋爱今天发的吗?恋爱第一天不算?

**Comment by sfyc23** [comment]
@yz-xlame 已修改，谢谢提醒。
