### ISSUE TITLE
Error: no "view" mailcap rules found for type "image/png"

### ISSUE THREAD

**Issue by klgentle** [sfyc23/EverydayWechat#109]
Getting uuid of QR code.
Downloading QR code.
Error: no "view" mailcap rules found for type "image/png"
Can't call method "get_value" on an undefined value at /usr/bin/mimeopen line 162.
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'QR.png'
Please scan the QR code to log in.

**Comment by sfyc23** [comment]
登录的那里 itchat.auto_login() 设置为 enableCmdQR=2 试试

**Comment by klgentle** [comment]
我看了下，itchat.auto_login()确实是 enableCmdQR=2


$ grep -rn auto_login *
hongmeng.py:28:def is_online(auto_login=False):
hongmeng.py:31:    :param auto_login: bool,当为 Ture 则自动重连(默认为 False)。
hongmeng.py:48:    if not auto_login:  # 不自动登录，则直接返回 False
hongmeng.py:57:            itchat.auto_login(enableCmdQR=2, hotReload=(not is_forced_switch))
hongmeng.py:59:            itchat.auto_login(hotReload=(not is_forced_switch))
hongmeng.py:153:    if not is_online(auto_login=True):
Binary file __pycache__/hongmeng.cpython-36.pyc matches







------------------ Original ------------------

**Comment by Hayat21** [comment]
Error: no "view" mailcap rules found for type "image/png"
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening '/tmp/tmpywnpip80.PNG'
