### ISSUE TITLE
'User' object has no attribute 'nickName'

### ISSUE THREAD

**Issue by imxw** [sfyc23/EverydayWechat#112]
与文件传输助手聊天报这个错，在yaml文件中已经添加 文件传输助手 为自动回复了

**Comment by sfyc23** [comment]
升级 itchat 的版本为到 >=1.3.10 。

**Comment by sfyc23** [comment]
> 升级 itchat 的版本为到 >=1.3.10 。

@imxw 不好意思，这应该是个 bug。已修改更新。
