### ISSUE TITLE
关于conda命令的问题

### ISSUE THREAD

**Issue by 1014763456** [sfyc23/EverydayWechat#114]
F:\study>conda install -r requirements.txt
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: unrecognized arguments: -r
这个应该怎么解决呢.google了也没有关于这个,我是什么配置错了嘛?

**Comment by sfyc23** [comment]
打开 anaconda prompt ，然后再使用 ： conda install -r requirements.txt 。

**Comment by 1014763456** [comment]
(base) F:\study\EverydayWechat-master>conda install -r requirements.txt
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: unrecognized arguments: -r
还是不行

**Comment by sfyc23** [comment]
> 打开 anaconda prompt ，然后再使用 ： conda install -r requirements.txt 。

不好意思，打错了，应该是 pip install -r requirements.txt 。
