### ISSUE TITLE
centos7 执行  pip3 install -r requirements.txt报错

### ISSUE THREAD

**Issue by Doslin** [sfyc23/EverydayWechat#118]
```
ERROR: Could not find a version that satisfies the requirement pyyaml==5.1.1 (from -r requirements.txt (line 5)) (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1)
ERROR: No matching distribution found for pyyaml==5.1.1 (from -r requirements.txt (line 5))
```
题意我找不到5.1.1的pyymal版本，
### 同时lxml==4.3.4也是找不到的

**Comment by Doslin** [comment]
> ```
> ERROR: Could not find a version that satisfies the requirement pyyaml==5.1.1 (from -r requirements.txt (line 5)) (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1)
> ERROR: No matching distribution found for pyyaml==5.1.1 (from -r requirements.txt (line 5))
> ```
> 
> 题意我找不到5.1.1的pyymal版本，
> 
> ### 同时lxml==4.3.4也是找不到的

于是我更改了requirements.txt中部分,结果如下
```
requests==2.22.0
beautifulsoup4==4.6.0
itchat==1.3.10
apscheduler==3.5.3
pyyaml==5.1
lxml==4.3.3
simplejson==3.16.0
```

**Comment by sfyc23** [comment]
我只是放的我电脑上的版本。我之后再试试吧，谢谢反馈。
