### ISSUE TITLE
服务器端登录成功之后直接 LOG OUT 是什么原因？

### ISSUE THREAD

**Issue by tongdev** [sfyc23/EverydayWechat#121]

**Comment by sfyc23** [comment]
应该是显示 bug.不影响使用的.

**Comment by nanzm** [comment]
同样的问题  运行 直接退出了

**Comment by nanzm** [comment]
我的操作是 git clone ，改配置， 然后安装依赖， 运行，  扫码登录   显示已开启自动回复   然后程序就退出命令行了

**Comment by sfyc23** [comment]
控制台输出什么呢。能截图，或者发一下输出日志吗 @nanzm

**Comment by nanzm** [comment]
![image](https://user-images.githubusercontent.com/12454813/59742456-4ade0e00-92a0-11e9-8b0a-d6fc74d0322f.png)

**Comment by tongdev** [comment]
今天把项目重新 download 了一份，重新在服务器上运行了一下可以了，莫名其妙的就好了。有这种问题的大家可以试一下。
