### ISSUE TITLE
你们这个自动回复也太恶心了吧

### ISSUE THREAD

**Issue by cyqqk** [sfyc23/EverydayWechat#125]
![微信图片_20190621111221](https://user-images.githubusercontent.com/43198241/59895070-b8f81180-9415-11e9-8e12-fbf09fc41c17.png)

**Comment by zxqfengdi** [comment]
老哥你用的哪个机器人

**Comment by cyqqk** [comment]
> 老哥你用的哪个机器人

**Comment by cyqqk** [comment]
一个AI

**Comment by sfyc23** [comment]
有点尴尬无语，但便宜的话，也不能说他们什么。还是玩图灵的接口吧

**Comment by qisenshi** [comment]
这个机器人应该是可以训练的，代码里用的应该是别人训练过的。。。

**Comment by itollei** [comment]
为啥我配置的机器人都不会回复消息呢

**Comment by sfyc23** [comment]
又添了好几种不同的机器人。
