### ISSUE TITLE
关于如何在服务器端扫描二维码登录的问题

### ISSUE THREAD

**Issue by zxqfengdi** [sfyc23/EverydayWechat#126]
- 该项目的微信登录依靠Itchat模块，itchat模块默认支持在命令行模式显示二维码。

![命令行二维码](https://user-images.githubusercontent.com/27198066/59895837-b2b76480-9418-11e9-8033-9d357a77b9fc.png)

- 但是该项目main目录下的hongmeng.py文件对登录时系统状态做了判断(注释部分)，代码如下：

![二维码](https://user-images.githubusercontent.com/27198066/59895431-2e181680-9417-11e9-8d2d-e7f63cf95d36.png)
当os.environ.get('MODE')为'server'时才会在终端显示二维码。但是我ssh连接到服务器时发现os.environ里面根本没有MODE这个键，所以程序会默认打开二维码让我用手机扫描登录，这样ssh连接就会报错导致登录失败。

- **解决方法**：不进行os.environ['MODE']值的判断，默认就在终端显示二维码就可以。代码修改在第二张图里面请参考。

**Comment by qisenshi** [comment]
遇到了同样的问题

**Comment by sfyc23** [comment]
已重新修改判断逻辑。
