### ISSUE TITLE
如果能在加一个回复模板就好了

### ISSUE THREAD

**Issue by 154016** [sfyc23/EverydayWechat#127]

**Comment by sfyc23** [comment]
能说说你希望的样子吗？

**Comment by 154016** [comment]
常见的字符替换就好,方便自行排版组织语言
比如:
{...} 天气预报
2019-06-21，{...}
【天气预报】{...}
【今日温度】{...}
【今日风速】{...}
【出行提示】{...}
{...}
宝贝这是我们在一起的第 {...} 天。
{....}

**Comment by sfyc23** [comment]
也是可以的，虽然在代码里大家也是可以自己改的。但有些人会觉得你写的这个模板更麻烦，我思考一下吧。

**Comment by haoyiping** [comment]
可以考虑加入 chatterbot 方便配置模板

**Comment by sfyc23** [comment]
> 可以考虑加入 chatterbot 方便配置模板

像是『一个AI』其实已经有配置模板的功能了，但是没几个人去看文档的。  
可以配置 chatterbot ，但大部分的朋友，只是想要一个「即简单又智能」的机器人。  
有点尴尬。

**Comment by sfyc23** [comment]
> 常见的字符替换就好,方便自行排版组织语言
> 比如:
> {...} 天气预报
> 2019-06-21，{...}
> 【天气预报】{...}
> 【今日温度】{...}
> 【今日风速】{...}
> 【出行提示】{...}
> {...}
> 宝贝这是我们在一起的第 {...} 天。
> {....}

你是说自定义顺序吧。在一起的多少天可以自定义了，总的顺序，我再想想怎么改。

**Comment by 372620040** [comment]
其实用腾讯的那个机器人还不错，我感觉比会聊天多了。。。
