### ISSUE TITLE
在docker运行  出现ModuleNotFoundError: No module named “yaml”

### ISSUE THREAD

**Issue by dishine** [sfyc23/EverydayWechat#129]

**Comment by Shine-di** [comment]
放到docker中运行时出现
![docker错误图](https://user-images.githubusercontent.com/38779907/59971566-f0e78c00-95b0-11e9-9a27-993cbceec166.png)

**Comment by sfyc23** [comment]
docker 没更新了，可能有用问题的。你直接使用可以吗。

**Comment by youcailize** [comment]
pip3 install pyyaml试试？
或者pip3 install -r requirments.txt试试
