### ISSUE TITLE
更改config.yaml机器人渠道(默认3改成1)后出现" ‘NoneType’ object is not subscriptable "

### ISSUE THREAD

**Issue by 7-Qwen** [sfyc23/EverydayWechat#134]
图灵机器人的APIKEY写上去了，除了图灵也试了一个AI。只要更改config_yaml中的bot_channel就会报错 ‘NoneType’ object is not subscriptable，请问怎么解决？

**Comment by 7-Qwen** [comment]
尝试更改common.py和data_collection.py但是无奈技艺不深，找不到问题所在,希望大佬分析一下OrZ

**Comment by sfyc23** [comment]
应该是 config_yaml 里的内容出错了。你加一下wx:sfyc1314，我拉你入群，你发一下截图。
