### ISSUE TITLE
它一直发送那个自动的提醒，没有自动回复

### ISSUE THREAD

**Issue by rememberBr** [sfyc23/EverydayWechat#136]

**Comment by rememberBr** [comment]
没有回复不知道是不是因为我的图灵机器人没有认证完成的原因，但是他一直发送那个定时提醒的内容就很尴尬了

**Comment by rememberBr** [comment]
有没有群可以交流啊？

**Comment by rememberBr** [comment]
![QQ截图20190626115052](https://user-images.githubusercontent.com/34575670/60149855-c2fc8480-9808-11e9-89b6-9202240e0942.jpg)

**Comment by sfyc23** [comment]
加wx:sfyc1314 拉你入群。备注：Github。

**Comment by sfyc23** [comment]
自动提醒是个bug，已更新解决。
