### ISSUE TITLE
配置图灵apiKey后，并没有自动回复呀。

### ISSUE THREAD

**Issue by itollei** [sfyc23/EverydayWechat#137]

**Comment by sfyc23** [comment]
你把日志发出来也行啊，脑补 debuff 还是有点难度的。

**Comment by itollei** [comment]
我设置自动回复的是微信小号，用微信小号发一直没有回复，终端也没有错误日志，而是一直在发那个定时任务。是因为我图灵上配置的机器人没认证的原因？bot_channel改成默认的3也是一样

**Comment by sfyc23** [comment]
30秒不间断自动回复，是发布版本时没有注释。现在已经更新。你的终端有打印什么内容吗。

**Comment by itollei** [comment]
已开启定时发送提醒功能...

启动定时自动提醒...
正在获取民国情话...
获取 杭州 的天气...
(1, 20)
(2, 19)
(3, 21)
(4, 21)
(5, 21)
(6, 22)
(7, 23)
(8, 23)
(9, 23)
(10, 23)
(11, 23)
获取星座屋数据 ...
获取今日星座运势成功！
获取明日星座运势成功！
2019-06-26 杭州市 多云 26℃ 东风 ≤3级 湿度：79%
我找到了你 便像是找到了真的自己
如果没有你
即使我爱了一百个人 或有一百个人爱我
我的灵魂也仍将永远彷徨着
宝贝这是我们在一起的第 625 天。
你脚下的蚂蚁


射手座今日运势（6月26日）
幸运颜色：黑色
幸运数字：3
- 综合运势:
今天你身边会有很多不理解的杂音，还好的你的心态乐观，能一笑而过。工作/学习上，你的热心助人，在旁人的眼中被掺杂了很多目的性，但你认为问心无愧也就没放在心上。感情方面，外界或许会有些闲言碎语，有伴人士要和伴侣保持沟通，明辨是非。
- 爱情运势:
单身者今天容易被感动，是桃花盛开的预兆。
- 事业学业:
与人沟通交接时保存记录，以免出错被推卸责任。
- 财富运势:
种草的东西又出了新品，按捺不住去剁手。
- 健康运势:
提防过敏性鼻炎，要远离花粉。


射手座明日运势（6月27日）
幸运颜色：红色
幸运数字：2
- 综合运势:
今天的运势起伏比较大，需要谨慎小心应对，切记不能得意忘形。工作/学习上，出色的表现容易成为小人的眼中钉，还好有贵人提点，能够顺利化险为夷。感情方面，有伴者的故意隐瞒会成为对方心中的那根刺，坦诚相待你会发现并没什么。
- 爱情运势:
过分推销自己，反而容易引起异性的反感哦！
- 事业学业:
把心态放平和些，不可大喜或是大悲。
- 财富运势:
有偏财运关照，容易成为中奖的幸运儿。
- 健康运势:
应酬交际过程中，应尽量少碰烟酒，量过伤身。

定时给『小号』发送的内容是:
2019-06-26 杭州市 多云 26℃ 东风 ≤3级 湿度：79%
我找到了你 便像是找到了真的自己
如果没有你
即使我爱了一百个人 或有一百个人爱我
我的灵魂也仍将永远彷徨着
宝贝这是我们在一起的第 625 天。
你脚下的蚂蚁


射手座今日运势（6月26日）
幸运颜色：黑色
幸运数字：3
- 综合运势:
今天你身边会有很多不理解的杂音，还好的你的心态乐观，能一笑而过。工作/学习上，你的热心助人，在旁人的眼中被掺杂了很多目的性，但你认为问心无愧也就没放在心上。感情方面，外界或许会有些闲言碎语，有伴人士要和伴侣保持沟通，明辨是非。
- 爱情运势:
单身者今天容易被感动，是桃花盛开的预兆。
- 事业学业:
与人沟通交接时保存记录，以免出错被推卸责任。
- 财富运势:
种草的东西又出了新品，按捺不住去剁手。
- 健康运势:
提防过敏性鼻炎，要远离花粉。


射手座明日运势（6月27日）
幸运颜色：红色
幸运数字：2
- 综合运势:
今天的运势起伏比较大，需要谨慎小心应对，切记不能得意忘形。工作/学习上，出色的表现容易成为小人的眼中钉，还好有贵人提点，能够顺利化险为夷。感情方面，有伴者的故意隐瞒会成为对方心中的那根刺，坦诚相待你会发现并没什么。
- 爱情运势:
过分推销自己，反而容易引起异性的反感哦！
- 事业学业:
把心态放平和些，不可大喜或是大悲。
- 财富运势:
有偏财运关照，容易成为中奖的幸运儿。
- 健康运势:
应酬交际过程中，应尽量少碰烟酒，量过伤身。

发送成功...


自动提醒消息发送完成...


只有这个

**Comment by sfyc23** [comment]
有登录之后有没有打印 『已开启图灵自动回复...』

**Comment by itollei** [comment]
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
已开启定时发送提醒功能...

启动定时自动提醒...
正在获取民国情话...
获取 杭州 的天气...


没有『已开启图灵自动回复...』这个提示

**Comment by sfyc23** [comment]
在 _config.yaml 中 的 auto_reply_names 中加上「文件传输助手」，你给文件传输助手发内容也无效吗。

**Comment by sfyc23** [comment]
不好意思，可能是出 bug 了，你重复下载代码试试。还是不行，你加一下 wx：sfyc1314。备注：Github 。我拉你进群里，帮你解决一下。

**Comment by itollei** [comment]
嗯嗯 好的 我重新下载代码再试试 还是不行就加wx骚扰下您 谢谢

**Comment by itollei** [comment]
重新clone代码后再修改配置、运行就可以自动回复了。多谢大神耐心指导。
