### ISSUE TITLE
设置两个时间

### ISSUE THREAD

**Issue by liuzongqi** [sfyc23/EverydayWechat#138]
能设置两个时间就好了，上午下午都能发。

**Comment by OceanWong1991** [comment]
![image](https://user-images.githubusercontent.com/17758711/60243493-f283bd80-98ea-11e9-8f0b-e6261dbafdb7.png)

@liuzongqi you can change yaml like that, I didn't test it

**Comment by sfyc23** [comment]
> 能设置两个时间就好了，上午下午都能发。

如果设置多个时间，那提醒的内容是不是也得做相应的调整，这样才合理。

**Comment by sfyc23** [comment]
@liuzongqi @OceanWong1991 新版本已可设置多个时间.
