### ISSUE TITLE
按照博主提示添加完一个AI的client_token运行程序提示_config.yaml文件配置错误？哪位大佬给解答下

### ISSUE THREAD

**Issue by CYi1113** [sfyc23/EverydayWechat#143]

**Comment by sfyc23** [comment]
![image](https://user-images.githubusercontent.com/7067207/60270416-f6333680-9922-11e9-8438-e331c28d1ba0.png)
注意这里面的空格。

**Comment by CYi1113** [comment]
> ![image](https://user-images.githubusercontent.com/7067207/60270416-f6333680-9922-11e9-8438-e331c28d1ba0.png)
> 注意这里面的空格。

现在运行程序提示：
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from everyday_wechat import main
  File "/Users/ccyi/Desktop/changyi/EverydayWechat/everyday_wechat/main.py", line 10, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ImportError: No module named apscheduler.schedulers.background

大佬我重新安装了依赖也不行

**Comment by sfyc23** [comment]
你安装的依赖与你运行的依赖可能不是同一个环境。
