### ISSUE TITLE
获取当日天气预报有问题

### ISSUE THREAD

**Issue by QinghangPeng** [sfyc23/EverydayWechat#144]
应该使用sojson这个文件获取当日天气预报，否则过了12点，仍然获取的昨天的天气预报

**Comment by sfyc23** [comment]
这个我倒是没有试过。不过默认的应该就是 sojson 这个文件获取天气的。

**Comment by QinghangPeng** [comment]
![image](https://user-images.githubusercontent.com/20389775/60320701-1ad3f080-99ad-11e9-867b-6d6e76ba9fba.png)
如图，引包没引对

**Comment by sfyc23** [comment]
嗯，谢谢提醒，提交包的时候没有注意到了。

**Comment by sfyc23** [comment]
已修改。
