### ISSUE TITLE
'dict' object has no attribute 'text'

### ISSUE THREAD

**Issue by tectal** [sfyc23/EverydayWechat#146]
运行run.py，并且
已开启图灵自动回复...
已开启定时发送提醒功能...
Start auto replying.
但是
在微信上面回复时，出现
'dict' object has no attribute 'text'

**Comment by sfyc23** [comment]
你用的是什么渠道的自动回复。

**Comment by tectal** [comment]
1,2,3都这样 自动回复都出现'dict' object has no attribute 'text'

**Comment by sfyc23** [comment]
你 itchat 的版本是多少？
