### ISSUE TITLE
请问如何部署在云服务器上？

### ISSUE THREAD

**Issue by g10guang** [sfyc23/EverydayWechat#15]
每天都在电脑中登陆微信实在不方便，如果能够让其运行在云服务上就方便很多了。我觉得这是一个common的需求。

**Comment by sfyc23** [comment]
部署服务器很简单，麻烦在于扫二维码登录。但不建议这么玩，微信的限制太多了，能保持在线时间也就一两天，然后就得重新登录。为这个项目不值。

**Comment by guanpengchn** [comment]
这个在电脑上登陆的时候办公就用不了了吧，所以项目确实挺好玩的，哈哈，不过不能总用

**Comment by yfxiongda** [comment]
> 部署服务器很简单，麻烦在于扫二维码登录。但不建议这么玩，微信的限制太多了，能保持在线时间也就一两天，然后就得重新登录。为这个项目不值。二维码登录也不是很难，可以把二维码download下来然后通过email发送什么的。

**Comment by yfxiongda** [comment]
> 部署服务器很简单，麻烦在于扫二维码登录。但不建议这么玩，微信的限制太多了，能保持在线时间也就一两天，然后就得重新登录。为这个项目不值。

二维码登录也不是很难，可以把二维码download下来然后通过email发送什么的。

**Comment by xingkong123600** [comment]
维持在线时间短是个问题。要时不时的登陆。。。

**Comment by sfyc23** [comment]
> 维持在线时间短是个问题。要时不时的登陆。。。

微信本身对接口的限制就多。

**Comment by qq727127158** [comment]
> 部署服务器很简单，麻烦在于扫二维码登录。但不建议这么玩，微信的限制太多了，能保持在线时间也就一两天，然后就得重新登录。为这个项目不值。

itchat的热加载机制影响不大。
