### ISSUE TITLE
关于一个AI的自动回复

### ISSUE THREAD

**Issue by Albbus** [sfyc23/EverydayWechat#151]
一个AI创建后，我在场景等各种地方创建了：“你叫什么”的回复，但是不论怎么样微信端回复的还是菲菲，然后会有很多比较容易引起反感的自动回复。（我知道与代码无关，但是一个AI论坛感觉已经没人了。）

**Comment by sfyc23** [comment]
已经在 readme 文件提示。现在又新添了俩。。
