### ISSUE TITLE
Itchat 登录保活

### ISSUE THREAD

**Issue by StormKid** [sfyc23/EverydayWechat#153]
由于基于itchat ，我现在也在根据它，重写一套框架，想把它弄到移动端去，但是有一点很严重的问题，那就是它的登录保活问题，它的hot 登录保活时间好像只有20分钟左右，这保活时间是如何控制到一天多的，新手求解，望指教指教~~

**Comment by sfyc23** [comment]
不也不清楚，有关 itchat 的问题，更建议去 itchat issues 讨论区。

**Comment by StormKid** [comment]
@sfyc23 谢谢，看到这些处理信息部分已经受教了！
