### ISSUE TITLE
ssh关闭后，wechaty也会断 用nohup，机器人收不到消息

### ISSUE THREAD

**Issue by PIPIPIKa** [sfyc23/EverydayWechat#154]
有没有好的解决办法

**Comment by sfyc23** [comment]
你来错地方了吧，朋友。。我用的是 itchat。

**Comment by PIPIPIKa** [comment]
我图方便少打了几个字，是ichat
我也找到解决的办法了，可以cat 一下nohup输出的out，然后扫码

Thunder Bouble <notifications@github.com>于2019年7月3日 周三19:34写道：
