### ISSUE TITLE
定时提醒与自动回复

### ISSUE THREAD

**Issue by poorsecretary** [sfyc23/EverydayWechat#158]
在config里面把is_auto_relay改成false之后发现运行的时候，虽然确实不会自动回复了，但是还是会显示start auto replying的情况。并且在显示Staat auto replying 的情况下不会发送定时提醒，手动CTRL+c倒是可以让它发送，但是就失去了让它定时发送的意义了。
PS：在config里面应该是auto_reply，写的是relay了

**Comment by sfyc23** [comment]
start auto replying 这句话是 itchat 的系统日志。不设置自动回复，定时提醒也是可以用的。这两个功能是互相独立的。
