### ISSUE TITLE
执行运行 出现以下报错

### ISSUE THREAD

**Issue by meikoul** [sfyc23/EverydayWechat#16]
ModuleNotFoundError: No module named 'requests'

**Comment by meikoul** [comment]
使用 pip install -r requirements.txt 安装所有依赖 我执行了这个

**Comment by sfyc23** [comment]
要不你单个安装:
```
pip install requests
```

**Comment by GaoJunjie1993** [comment]
代码中修改为直接运行：
   # 直接运行
    GFWeather().run()
======================================
/EverydayWechat-master$ sudo python3.6 run.py 

Traceback (most recent call last):
  File "run.py", line 22, in <module>
    run()
  File "run.py", line 11, in run
    GFWeather().run()
  File "/home/g02693/Documents/EverydayWechat-master/GFWeather.py", line 32, in __init__
    self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
  File "/home/g02693/Documents/EverydayWechat-master/GFWeather.py", line 55, in get_init_data
    girlfriend.get('wechat_name').strip()
AttributeError: 'NoneType' object has no attribute 'get'

没有弹出登录二维码，直接运行报错。

**Comment by GaoJunjie1993** [comment]
if __name__ == '__main__':
    # 直接运行
    GFWeather().run()
========================
/EverydayWechat-master$ sudo python3.6 run.py 
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    run()
  File "run.py", line 11, in run
    GFWeather().run()
  File "/home/Documents/EverydayWechat-master/GFWeather.py", line 32, in __init__
    self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
  File "/home/Documents/EverydayWechat-master/GFWeather.py", line 55, in get_init_data
    girlfriend.get('wechat_name').strip()
AttributeError: 'NoneType' object has no attribute 'get'

直接运行报错

**Comment by sfyc23** [comment]
> # if **name** == '**main**':
> # 直接运行
> GFWeather().run()
> /EverydayWechat-master$ sudo python3.6 run.py
> Traceback (most recent call last):
> File "run.py", line 22, in 
> run()
> File "run.py", line 11, in run
> GFWeather().run()
> File "/home/Documents/EverydayWechat-master/GFWeather.py", line 32, in **init**
> self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
> File "/home/Documents/EverydayWechat-master/GFWeather.py", line 55, in get_init_data
> girlfriend.get('wechat_name').strip()
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> 直接运行报错

不同的问题请新开一个 issues 。您的这个错误信息不全。
