### ISSUE TITLE
Undefined names 'city_dict' and 'init'

### ISSUE THREAD

**Issue by cclauss** [sfyc23/EverydayWechat#163]
Why no automated testing?

[flake8](http://flake8.pycqa.org) testing of https://github.com/sfyc23/EverydayWechat on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./everyday_wechat/control/weather/sojson.py:83:17: F821 undefined name 'city_dict'
    city_code = city_dict.get(city_name, None)
                ^
./everyday_wechat/utils/config.py:61:5: F821 undefined name 'init'
    init()
    ^
2     F821 undefined name 'city_dict'
2
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by sfyc23** [comment]
Thank you for your feedback, I will participate in your suggestion to modify later.
