### ISSUE TITLE
回复得太快，加上某些回复没有逻辑，很容易被对方意识到是机器人。

### ISSUE THREAD

**Issue by marithy** [sfyc23/EverydayWechat#175]
可不可以加上几秒的延迟发送，或者能够发送‘’对方正在输入”的状态就好了。

**Comment by wangxing1986** [comment]
你自己在friend_helper.py的49行之前加上，time.sleep不就可以了吗

**Comment by sfyc23** [comment]
『对方正在输入』这个，网页微信做不到啊。延迟倒可以之后加上这个选项。
