### ISSUE TITLE
爬取天气时，时间有问题

### ISSUE THREAD

**Issue by itswl** [sfyc23/EverydayWechat#176]
我早上7点，有些是今日有些事昨日

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by sfyc23** [comment]
有一个属性是 is_tomorrow 。你是不是设置成 True 了。

**Comment by itswl** [comment]
是API更新不及时，早上7点的时候，有的获取的还是昨日数据。

**Comment by houjiaxing** [comment]
我也发现了这个问题，is_tomorrow 为 False，早5点获取天气数据后因为取的是data[0] 很大几率出现昨日数据，早7点有一定几率取到昨日数据。

**Comment by sfyc23** [comment]
已解决此问题
