### ISSUE TITLE
为了你的帐号安全，此微信号不能登录网页微信

### ISSUE THREAD

**Issue by JeffreyBool** [sfyc23/EverydayWechat#179]
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by wave2588** [comment]
请问你解决了吗?
