### ISSUE TITLE
求怎样才能登陆网页版的微信

### ISSUE THREAD

**Issue by tr1912** [sfyc23/EverydayWechat#184]
本人尝试过好多次了，无论是新的微信号还是老微信号，都登陆不了网页版的微信

**Comment by G-BlueSummer** [comment]
腾讯准备弃用网页版了吧😭

**Comment by sfyc23** [comment]
没有解决办法！！

**Comment by LiChangXing** [comment]
网页微信17年后所有新号都不行了，你们看下这个吧 商业收费的https://wkteam.gitbook.io/api/

**Comment by sfyc23** [comment]
@LiChangXing 您能别在我的这个项目下推广了，行吗？？
