### ISSUE TITLE
6月份登陆正常，今天发现了这个问题，也有人遇到么

### ISSUE THREAD

**Issue by Rover-Geek** [sfyc23/EverydayWechat#187]
Getting uuid of QR code.
Downloading QR code.
[WinError 1155] 没有应用程序与此操作的指定文件有关联。: 'QR.png'
登录失败。
程序已退出...

**Comment by Rover-Geek** [comment]
经提醒是因为我的电脑没有按照默认打开图片的软件。

**Comment by sfyc23** [comment]
这个是你电脑没有指定默认找开图片的软件。
