### ISSUE TITLE
断网后程序会中断

### ISSUE THREAD

**Issue by Voidering** [sfyc23/EverydayWechat#19]
即拿即用，抱拳了老铁。网络不太稳定，一掉线程序就会中断。怎么样才能保证只要在发送时间有网就能发送成功，而其他时间就算断网了程序还能继续跑呢？

**Comment by sfyc23** [comment]
可以加上一个断网提醒。发送数据时，如果断网了，把登录二维码发送到微信上。之后再补充吧。
