### ISSUE TITLE
扫描二维码登录时，提示无法通过网页登录

### ISSUE THREAD

**Issue by Zakariyya** [sfyc23/EverydayWechat#198]
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
Start auto replying.
登录失败。
程序已退出...

**Comment by zachary1212** [comment]
huh

**Comment by wave2588** [comment]
请问你解决了吗?

**Comment by allanj** [comment]
同问
