### ISSUE TITLE
locale报错

### ISSUE THREAD

**Issue by PhrenoVermouth** [sfyc23/EverydayWechat#2]
看了下closed的issue， 改了一下GFweather.py里边的对应行，依然提示unsupported locale setting。难道是英文系统的锅？

小白求教。

**Comment by fusheng12** [comment]
我用的Linux跑的，locale.setlocale(locale.LC_CTYPE, 'zh_CN.UTF-8')写成这样可以正常使用。

**Comment by TLMichael** [comment]
> 我用的Linux跑的，locale.setlocale(locale.LC_CTYPE, 'zh_CN.UTF-8')写成这样可以正常使用。

多谢！

**Comment by olingrobin** [comment]
> 我用的Linux跑的，locale.setlocale(locale.LC_CTYPE, 'zh_CN.UTF-8')写成这样可以正常使用。

多写

**Comment by olingrobin** [comment]
> 我用的Linux跑的，locale.setlocale(locale.LC_CTYPE, 'zh_CN.UTF-8')写成这样可以正常使用。

多谢

**Comment by sfyc23** [comment]
```
today_time = datetime.now().strftime('%Y{y}%m{m}%d{d} %H:%M:%S').format(y='年', m='月', d='日')
```
已更改成这种方法，不用考虑运行环境。
