### ISSUE TITLE
不能给微信群发消息么

### ISSUE THREAD

**Issue by xhily** [sfyc23/EverydayWechat#20]
想着每天给家人报天气预报

**Comment by sfyc23** [comment]
也可以发群，但在这个项目没有实现。之后我再加上吧。

**Comment by xhily** [comment]
> 也可以发群，但在这个项目没有实现。之后我再加上吧。

感谢老哥，然后我这边用的谷歌云服务 运行成功后关闭终端 过上几分钟 网页登录就会退出 是我操作有问题么 谢谢了

**Comment by wcp1231** [comment]
> 想着每天给家人报天气预报

还以为有个女朋友群 :)

**Comment by Gengxin-Zhang** [comment]
> > 想着每天给家人报天气预报
> 
> 还以为有个女朋友群 :)

hhhhhhhhhhhh那这就可太秀了

**Comment by Jerry-Lau** [comment]
> > 想着每天给家人报天气预报
> 
> 还以为有个女朋友群 :)

秀出天际

**Comment by Abyssali** [comment]
> > 想着每天给家人报天气预报
> 
> 还以为有个女朋友群 :)

可太优秀了

**Comment by skyhuangdan** [comment]
> > 想着每天给家人报天气预报
> 
> 还以为有个女朋友群 :)

秀儿是你吗?

**Comment by sfyc23** [comment]
下个版本加。

**Comment by ZhizhenWang** [comment]
下一个版本「后宫版」

**Comment by sfyc23** [comment]
现在的版本已经支持了。
