### ISSUE TITLE
网页版微信现在是都不能登陆了吗，，，有没有解决办法，我的登录不了

### ISSUE THREAD

**Issue by wfs123456** [sfyc23/EverydayWechat#204]
网页版微信现在是都不能登陆了吗，，，有没有解决办法，我的登录不了

**Comment by chunge16** [comment]
我也是这样

**Comment by pangh-space** [comment]
我也遇到了网页版本无法登录，有没有解决办法？

**Comment by ychost** [comment]
一样的，操蛋

**Comment by sfyc23** [comment]
除了换号，没有其他的办法

**Comment by wangliewei** [comment]
能不能别给我发邮件了



---原始邮件---
发件人: "Thunder Bouble"<notifications@github.com&gt;
发送时间: 2020年5月15日(周五) 上午10:20
收件人: "sfyc23/EverydayWechat"<EverydayWechat@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [sfyc23/EverydayWechat] 网页版微信现在是都不能登陆了吗，，，有没有解决办法，我的登录不了 (#204)




 
除了换号，没有其他的办法
