### ISSUE TITLE
天气无法获取

### ISSUE THREAD

**Issue by weiyouwozuiku** [sfyc23/EverydayWechat#209]
启动定时自动提醒...
获取天气信息...
HTTPConnectionPool(host='t.weather.sojson.com', port=80): Max retries exceeded with url: /api/weather/city/101190101 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12780d1128>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by Priestch** [comment]
@weiyouwozuiku 获取天气的 API 不能用了
把 `weather_url = 'http://t.weather.sojson.com/api/weather/city/{}'.format(city_code)` 改成
`weather_url = 'http://t.weather.itboy.net/api/weather/city/{}'.format(city_code)`

**Comment by weiyouwozuiku** [comment]
好的，谢谢。
