### ISSUE TITLE
每次运行都要登录吗？

### ISSUE THREAD

**Issue by LazyLutra** [sfyc23/EverydayWechat#22]
每次运行时都会生成二维码，提示我扫描登录。
还是我姿势不对

**Comment by sfyc23** [comment]
可将：
```
 itchat.auto_login()
```
修改成：
```
# 通过如下命令登陆，即使程序关闭，一定时间内重新开启也可以不用重新扫码。
itchat.auto_login(hotReload=True)
```
即可。

请参考 [Itchat](https://github.com/littlecodersh/ItChat)。

**Comment by LazyLutra** [comment]
> 可将：
> 
> ```
>  itchat.auto_login()
> ```
> 
> 修改成：
> 
> ```
> # 通过如下命令登陆，即使程序关闭，一定时间内重新开启也可以不用重新扫码。
> itchat.auto_login(hotReload=True)
> ```
> 
> 即可。
> 
> 请参考 [Itchat](https://github.com/littlecodersh/ItChat)。

谢谢老哥

**Comment by yizibi** [comment]
我也遇到了，感谢

**Comment by yizibi** [comment]
我也是，每次发完消息后，就弹出二维码让我重新登录

**Comment by sfyc23** [comment]
@yizibi 

已更新修改成 hotReload。
