### ISSUE TITLE
运行了之后报错

### ISSUE THREAD

**Issue by QiHangLuo** [sfyc23/EverydayWechat#24]
不论是在cmd还是在pycharm中,运行之后都会报错,求助
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    run()
  File "run.py", line 9, in run
    gfweather().run()
  File "D:\git\git\repository\pythonHomework\EverydayWechat\GFWeather.py", line 18, in __init__
    self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
  File "D:\git\git\repository\pythonHomework\EverydayWechat\GFWeather.py", line 37, in get_init_data
    girlfriend.get('wechat_name').strip()
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by yfxiongda** [comment]
加1

**Comment by yfxiongda** [comment]
一样的报错，又解决吗？

**Comment by yfxiongda** [comment]
找出问题了，是config文件不对，最后几行不要注释，直接删掉就可以了

**Comment by FuckReally** [comment]
这是时间配置的有问题吗
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from GFWeather import gfweather
  File "/home/ray/app/EverydayWechat-master/GFWeather.py", line 29
    init_msg = f"每天定时发送时间：{alarm_timed}\n"
                                         ^
SyntaxError: invalid syntax

**Comment by vanvae** [comment]
> 这是时间配置的有问题吗
> Traceback (most recent call last):
> File "run.py", line 1, in 
> from GFWeather import gfweather
> File "/home/ray/app/EverydayWechat-master/GFWeather.py", line 29
> init_msg = f"每天定时发送时间：{alarm_timed}\n"
> ^
> SyntaxError: invalid syntax

时间格式是yyyy-mm-dd吗？

**Comment by Kezbol** [comment]
我这报错no module named yaml,pip3也没有找到

**Comment by sfyc23** [comment]
> 这是时间配置的有问题吗
> Traceback (most recent call last):
> File "run.py", line 1, in 
> from GFWeather import gfweather
> File "/home/ray/app/EverydayWechat-master/GFWeather.py", line 29
> init_msg = f"每天定时发送时间：{alarm_timed}\n"
> ^
> SyntaxError: invalid syntax

你的这个问题，应该是 Python 版本的问题。这是 Python 3.6 之后 的语法 。

**Comment by QiHangLuo** [comment]
> 找出问题了，是config文件不对，最后几行不要注释，直接删掉就可以了

哇,感谢
