### ISSUE TITLE
提示昵称错误？调试没错误，扫码登陆提示昵称错误？

### ISSUE THREAD

**Issue by Githup-Guitarlc** [sfyc23/EverydayWechat#25]
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Log in time out, reloading QR code.
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as Lc
登录成功
昵称错误

求大佬翻牌喵喵吖

**Comment by Githup-Guitarlc** [comment]
此问题终结 ，萌新没有仔细查看文档。已成功运行~~学习了。感谢大佬

**Comment by gary101** [comment]
@Githup-Guitarlc 您好，我也遇到这个问题，始终找不到问题原因，能否告知一下问题出在哪？感激不尽！

**Comment by sfyc23** [comment]
> @Githup-Guitarlc 您好，我也遇到这个问题，始终找不到问题原因，能否告知一下问题出在哪？感激不尽！

是用微信昵称或者备注名，而不是微信号。
