### ISSUE TITLE
运行出错，索引超出范围

### ISSUE THREAD

**Issue by sunyongsheng** [sfyc23/EverydayWechat#32]
在 every_msg = soup_texts.find_all('div', class_='fp-one-cita')[0].find('a').text 语句处提示错误：
list index out of range

**Comment by SimonInGayHub** [comment]
+1

**Comment by sfyc23** [comment]
网页改规则了，我修改一下。

**Comment by sfyc23** [comment]
应该不会报错了。但你们这个问题应该是本地网络请求出错了

**Comment by sunyongsheng** [comment]
用新的代码可以，但是如果把新的GFWeather代码复制到原来的中还是会重现错误

**Comment by sfyc23** [comment]
> 用新的代码可以，但是如果把新的GFWeather代码复制到原来的中还是会重现错误

你试试这个：
```
print(requests.get('https://www.baidu.com').text)
```
看能打印出什么 。
