### ISSUE TITLE
服务器上运行怎么调出二维码扫描登陆

### ISSUE THREAD

**Issue by FuckReally** [sfyc23/EverydayWechat#34]
centos7上运行，二维码怎么扫？
Getting uuid of QR code.
Downloading QR code.
xdg-open: no method available for opening 'QR.png'
Please scan the QR code to log in.

**Comment by xhily** [comment]
老哥我是这样做的 ：我的宝塔面板 运行后 文件管理里面下载图片OR预览  扫码就行

**Comment by sfyc23** [comment]
保存图片然后发邮件到自己邮箱里，扫码登录。

**Comment by liuzheng** [comment]
https://github.com/sfyc23/EverydayWechat/blob/master/GFWeather.py#L88
这一行注释切换一下，或者吧True改为1或者2
具体不懂去看itchat的api

**Comment by FuckReally** [comment]
> https://github.com/sfyc23/EverydayWechat/blob/master/GFWeather.py#L88
> 这一行注释切换一下，或者吧True改为1或者2
> 具体不懂去看itchat的api

**Comment by FuckReally** [comment]
itchat.auto_login(enableCmdQR=True)  true在linux中显示的二维码有问题，改为2成功解决，四楼正解，谢谢~

**Comment by sfyc23** [comment]
> itchat.auto_login(enableCmdQR=True) true在linux中显示的二维码有问题，改为2成功解决，四楼正解，谢谢~

你同步一下代码，这个昨天已经更改了。

**Comment by jubyshu** [comment]
@sfyc23 我在服务器上运行出来的二维码是这样的，请问应该怎么办，不太懂。sfyc23
![Screen Shot 2019-06-13 at 12.53.41 PM.png](https://i.loli.net/2019/06/13/5d01d712a6fef53966.png)

**Comment by ikingye** [comment]
export MODE='server' && python run.py
