### ISSUE TITLE
我在v2上看到有个土味情话的api

### ISSUE THREAD

**Issue by tomatoF** [sfyc23/EverydayWechat#38]
可以发送一句土味情话
response = requests.get("https://api.lovelive.tools/api/SweetNothings")
itchat.send(str(response.text),'filehelper')
俺不会用git

**Comment by QSCTech-Sange** [comment]
可以，牛皮，我改改提个pr

**Comment by QSCTech-Sange** [comment]
我已经提交pr了，我这里测试完成，你康康你能不能使用。

**Comment by Gengxin-Zhang** [comment]
可以的，强
