### ISSUE TITLE
girlfriend_infos配置项建议换成girlfriend_info

### ISSUE THREAD

**Issue by garenchan** [sfyc23/EverydayWechat#41]
女朋友用复数？
- 首先，能用这个程序的大多数是程序猿，能有一个女朋友就不错了；
- 其次，同时拥有多个女朋友那不是渣男吗，不符合社会主义核心价值观

综上所述，用单数会不会更好？:joy:
https://github.com/sfyc23/EverydayWechat/blob/5796215a35b83b689a75b36ac0eaed4a054f5968/GFWeather.py#L37-L52

**Comment by alanchenchen** [comment]
hhhhhhhhh，可太秀了哦

**Comment by sfyc23** [comment]
命名可比开发要难。

**Comment by sfyc23** [comment]
女权警告
