### ISSUE TITLE
似乎不支持树莓派 Python 3.5 虽然做了简单修改能跑

### ISSUE THREAD

**Issue by liuzheng** [sfyc23/EverydayWechat#42]
树莓派的python是3.5的，代码使用了3.6的新特性，部分修改好跑起来还是没法自动发。
是否考虑兼容？
我个人考虑用go写一个了

**Comment by sfyc23** [comment]
本来就是想写的玩来着，没想到这么多人用，稍后修改兼容。

**Comment by sfyc23** [comment]
@liuzheng  已兼容 Python 3.5。
