### ISSUE TITLE
请问下，import失败

### ISSUE THREAD

**Issue by Nono17** [sfyc23/EverydayWechat#47]
ImportError: cannot import name 'gfweather' from 'GFWeather'
这如何解决

**Comment by sfyc23** [comment]
能粘全一点吗，是在哪个文件中的。

**Comment by qq727127158** [comment]
依赖都下载了吗

**Comment by Nono17** [comment]
> 能粘全一点吗，是在哪个文件中的。

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from GFWeather import gfweather
ImportError: cannot import name 'gfweather' from 'GFWeather' (D:\program\EverydayWechat\GFWeather.py)

**Comment by Nono17** [comment]
> 依赖都下载了吗

都下了

**Comment by sfyc23** [comment]
@Nono17 应该是有一次我更新的时候，忘了更新 run.py 文件。
你同步一下 git。
或者你把 run.py 文件：
```
from GFWeather import gfweather
```
修改成：
```
from GFWeather import GFWeather
```
