### ISSUE TITLE
想知道怎么算是成功了

### ISSUE THREAD

**Issue by L-is-0** [sfyc23/EverydayWechat#53]
显示登录以后就会自动发送消息吗，有没有确认信息说会几点发给谁呢

**Comment by sfyc23** [comment]
预计是你每天固定的时间发送一条问候语句。这个固定的时间是在 _config.yaml 文件的  alarm_timed 设置的。发给谁，也是在 _config.yaml 文件设置的。  
  这只是提供一个思路，其实还有很多问题。这个项目是在 [ItChat] (https://github.com/littlecodersh/ItChat)的基础上进行开发的。这个有一个很大的问题是如何保持长时间在线。
