### ISSUE TITLE
项目拉下来，能跑，可是就是不会提示登陆，不知是啥原因，

### ISSUE THREAD

**Issue by chen366690712** [sfyc23/EverydayWechat#54]
[100%]

=============================== warnings summary ===============================
run.py::test_run
  /Users/xhchen/PycharmProjects/EverydayWechat/GFWeather.py:29: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    config = yaml.load(f)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================== 1 passed, 1 warnings in 0.73 seconds =====================
Process finished with exit code 0

**Comment by chen366690712** [comment]
昵称错误 -
Login successfully as 诺
对过微信号，用账号也不行，怪了。不知在那错了。

**Comment by reflex-spec** [comment]
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

这个错误提示

**Comment by chen366690712** [comment]
> YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> 
> 这个错误提示

这个我更改为：
 #config = yaml.load(f) #这个是原来的
            config = yaml.load(f, Loader=yaml.FullLoader)## 这个是我现在的。

**Comment by reflex-spec** [comment]
> > YAMLLoadWarning：不使用Loader = ...调用yaml.load（），因为默认的Loader是不安全的。有关详细信息，请阅读https://msg.pyyaml.org/load。
> > 这个错误提示
> 
> 这个我更改为：
> #config = yaml.load（f）＃这个是原来的
> config = yaml.load（f，Loader = yaml.FullLoader）##这个是我现在的。

我也是这样的   也没有登录的提示

**Comment by gary101** [comment]
同样问题，程序运行时终端显示内容正常且显示发送成功，但是永远不提示登录。
都没登陆怎么会发送正常？程序假测？

**Comment by gary101** [comment]
抱歉，是要将run.py里的主程序改一下：
`if __name__ == '__main__':
    test_run()
    # run()`
改为
`if __name__ == '__main__':
    # test_run()
    run()`

**Comment by chen366690712** [comment]
> if __name__ == '__main__': # test_run() run()

抱歉，还是没法跑起来。这个我就是从run.py 中运行无法登陆，直接运行/EverydayWechat/GFWeather.py 又可以出来扫码。
搞不懂！

**Comment by chen366690712** [comment]
![image](https://user-images.githubusercontent.com/23465637/59251628-d7634d80-8c5c-11e9-810e-7e467267553a.png)
# #

**Comment by sfyc23** [comment]
@chen366690712 
你同步一下最新代码。  
这一行应该修改成：
```
 config = yaml.load(file, Loader=yaml.Loader)
```

**Comment by sfyc23** [comment]
@chen366690712  或者您加一下我的微信：sfyc_23。
