### ISSUE TITLE
执行之后报错，没有登陆二维码

### ISSUE THREAD

**Issue by reflex-spec** [sfyc23/EverydayWechat#56]
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
 
这行应该修改成什么样 config = yaml.load(f)

**Comment by sfyc23** [comment]
你是不是 clone 错了。你同步一下最新代码。
```
 config = yaml.load(file, Loader=yaml.Loader)
```

**Comment by reflex-spec** [comment]
照您这样指定了参数是没报错了   但是直接就这样显示了
![image](https://user-images.githubusercontent.com/51686032/59244238-3bc6e280-8c46-11e9-8591-d4762d4da061.png)

**Comment by reflex-spec** [comment]
> 你是不是clone错了。你同步一下最新代码。
> 
> ```
>  config = yaml.load(file, Loader=yaml.Loader)
> ```

同步您最新的代码后运行直接这样显示了
![image](https://user-images.githubusercontent.com/51686032/59244290-5dc06500-8c46-11e9-933b-399f891a26ef.png)

**Comment by sfyc23** [comment]
打印的日志看起来没有什么问题了。
