### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by 103style** [sfyc23/EverydayWechat#58]
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

You can't get access to internet or wechat domain, so exit.

**Comment by sfyc23** [comment]
你试试[网页端微信](https://wx.qq.com/):  https://wx.qq.com/ 你能登录吗。

**Comment by 103style** [comment]
会有个 不安全的 拦截

**Comment by sfyc23** [comment]
> 会有个 不安全的 拦截

那你的微信号可能就玩不了这个了。

**Comment by 103style** [comment]
应该是 和 网络 有关， 公司网络可能有限制吧

**Comment by sfyc23** [comment]
至少得能登录上网页微信 。itchat 是基于网页微信做的 api 接口。
