### ISSUE TITLE
刚刚拉项目下来，然后直接执行行run,不会出来二维码，登陆

### ISSUE THREAD

**Issue by chen366690712** [sfyc23/EverydayWechat#60]
Testing started at 15:27 ...
/usr/local/bin/python3.7 /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_pytest_runner.py --path /Users/xhchen/PycharmProjects/EverydayWechat2/run.py
Launching pytest with arguments /Users/xhchen/PycharmProjects/EverydayWechat2/run.py in /Users/xhchen/PycharmProjects/EverydayWechat2

============================= test session starts ==============================
platform darwin -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /Users/xhchen/PycharmProjects/EverydayWechat2collected 1 item

run.py .**************************************************
每天定时发送时间：1:48
格言获取渠道：词霸(每日英语)
女朋友的微信昵称：古典
	女友所在城市名称：桂林
	在一起的第一天日期：2017-10-10
	最后一句为：来自最爱你的我。
女朋友的微信昵称：陈老师
	女友所在城市名称：朝阳区
	在一起的第一天日期：2018-11-11
	最后一句为：来自你俊美的老公。

**************************************************
获取相关信息...
获取格言信息（双语）...
获取天气信息...
给『古典』发送的内容是:
2019年06月11日 15:27:20
宝贝这是我们在一起的第 609 天。
关好门窗，外出避开低洼地。
温度 : 23.0℃/27.0℃
北风 : <3级
空气 : 39.0
The tragedy of life is not so much what men suffer, but what they miss.
生活的悲剧不在于人们受多少苦，而在于人们错过了什么。
来自最爱你的我。

获取天气信息...
给『陈老师』发送的内容是:
2019年06月11日 15:27:20
宝贝这是我们在一起的第 212 天。
阴晴之间，谨防紫外线侵扰。
温度 : 22.0℃/32.0℃
西风 : <3级
空气 : 76.0
The tragedy of life is not so much what men suffer, but what they miss.
生活的悲剧不在于人们受多少苦，而在于人们错过了什么。
来自你俊美的老公。

发送成功...

                                                                 [100%]

=========================== 1 passed in 0.97 seconds ===========================
Process finished with exit code 0

**Comment by sfyc23** [comment]
你已经开了一个 issues #54 。在那里我有回复你的。
