### ISSUE TITLE
我运行成功了，但没有自动回复呀

### ISSUE THREAD

**Issue by mackyuqimack** [sfyc23/EverydayWechat#64]
我运行成功了，但是别人给我发消息，并没有自动回复，请问是什么原因

**Comment by mackyuqimack** [comment]
这个程序感觉太骚了，期望这个程序能添加多个定时任务，目前好像一天只能有一个任务。
还有希望自动回复功能尽快增加，不然一直挂着的意义不是很大

**Comment by sfyc23** [comment]
怎么说呢，实现并不难。但写文档太麻烦了。没有加自动回复呢。

**Comment by mackyuqimack** [comment]
> 怎么说呢，实现并不难。但写文档太麻烦了。没有加自动回复呢。

我看你准备加图灵机器人，不知道什么时候能加好，如果api申请的麻烦的话，可以试试微软小冰也支持微信

**Comment by sfyc23** [comment]
已经写好了。但是代码有点乱。还没有 合并 到版本中。

**Comment by itollei** [comment]
自动回复准备什么时候上呢

**Comment by sfyc23** [comment]
> 自动回复准备什么时候上呢

@itollei 看一下文档，已经做好了。
