### ISSUE TITLE
登陆成功提示但是报错提示昵称有误

### ISSUE THREAD

**Issue by lhls11** [sfyc23/EverydayWechat#65]
我在centos7 上 安装的python3.7 跑的代码  然后出现二维码登录提示成功  然后报错   我调试了下  是去微信获取朋友列表时候返回为空  报 list index out of range  
74             try:
 75                 if itchat.search_friends():
 76                     print(22)
 77                     return True
 78             except Exception as e:
 79                 print(format(e))
 80                 return False
 81             return True
79行报的  为什么登陆成功后获取列表失败呢
Login successfully as 暗杠
登录成功11
昵称有误

**Comment by sfyc23** [comment]
是用微信昵称或者备注名，而不是微信号。

**Comment by lhls11** [comment]
好的  可以了  谢了  大神  你可以改成支持微信号吗  不然有的昵称有特殊图片那种  无法配置啊 哈哈哈

**Comment by sfyc23** [comment]
> 好的 可以了 谢了 大神 你可以改成支持微信号吗 不然有的昵称有特殊图片那种 无法配置啊 哈哈哈

暂时应该是没法，itchat 的这个接口本来是可以的，但后来被微信自己做限制了。  
不过用备注名就好了，毕竟：**再 NB 的用户名也敌不过备注名啊**。
