### ISSUE TITLE
能不能实现一个撩妹的功能？

### ISSUE THREAD

**Issue by future-c** [sfyc23/EverydayWechat#66]
RT。
希望能出一个撩妹的功能。

**Comment by sfyc23** [comment]
有那样的 api 吗。有的话，后续加上这个功能。

**Comment by cbbfcd** [comment]
给附近的异性每天发情话？

**Comment by sfyc23** [comment]
> 给附近的异性每天发情话？

醒醒朋友，你的这个想法太危险了。

**Comment by cbbfcd** [comment]
> > 给附近的异性每天发情话？
> 
> 醒醒朋友，你的这个想法太危险了。

哈哈哈哈哈，等你明天重构算了。
