### ISSUE TITLE
Mac 执行报错

### ISSUE THREAD

**Issue by xuxueyong** [sfyc23/EverydayWechat#69]
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from GFWeather import GFWeather
  File "/Users/apple/Downloads/EverydayWechat-master/GFWeather.py", line 8, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'

**Comment by sfyc23** [comment]
缺少库
使用 :
```
pip install -r requirements.txt 
```
安装所有依赖库

**Comment by github641** [comment]
➜  EverydayWechat-master pip3 install -r requirements.txt
Collecting requests (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement requests (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for requests (from -r requirements.txt (line 1))


@sfyc23 Python 3.5.0，也是 Mac 执行的时候，麻烦看下

**Comment by sfyc23** [comment]
要不手动安装这些库也行;  
```
pip3 install 库1
pip3 install 库2
……
```

**Comment by tianly123** [comment]
安装依赖后还是报错，我的是无法识别 APScheduler

**Comment by WhySRZ** [comment]
> 安装依赖后还是报错，我的是无法识别 APScheduler

手动一个一个安装吧
