### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wangyingbo** [sfyc23/EverydayWechat#7]
![image](https://user-images.githubusercontent.com/12741589/58459949-2a1e0f00-815f-11e9-8b34-5a27b6270593.png)

**Comment by Awelling2** [comment]
同样问题

**Comment by sfyc23** [comment]
这个是 Python  3 的语法。

**Comment by Awelling2** [comment]
'root@Awelling:/home/Ea# python3 run.py
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    run()
  File "run.py", line 11, in run
    gfweather().run()
  File "/home/Ea/GFWeather.py", line 22, in __init__
    self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
  File "/home/Ea/GFWeather.py", line 30, in get_init_data
    config = yaml.load(f, loader=yaml.FullLoader)
TypeError: load() got an unexpected keyword argument 'loader''

**Comment by sfyc23** [comment]
> 用python3运行报yaml的错 尝试了一下Google的改法加loader=yaml.FullLoader运行还是报错······
> root@Awelling:/home/Ea# python3 run.py
> Traceback (most recent call last):
> File "run.py", line 23, in 
> run()
> File "run.py", line 11, in run
> gfweather().run()
> File "/home/Ea/GFWeather.py", line 22, in **init**
> self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
> File "/home/Ea/GFWeather.py", line 30, in get_init_data
> config = yaml.load(f, loader=yaml.FullLoader)
> TypeError: load() got an unexpected keyword argument 'loader'

你单独运行一下 yaml  试试，可以是你环境的问题。

**Comment by lovejianglz** [comment]
python 好像 3.7 之后才支持  f“XXXX”  这种语法

**Comment by sfyc23** [comment]
> python 好像 3.7 之后才支持 f“XXXX” 这种语法

Python  3.6 以上就支持了。
