### ISSUE TITLE
希望加入自动聊天功能

### ISSUE THREAD

**Issue by L1cardo** [sfyc23/EverydayWechat#80]
希望能够加入和女友聊天的功能，应该会用到图灵机器人
有大佬已经实现了，但是我没有找到相关资料

![8B2663A5-34E5-40EE-B758-9EF8790BE9AF](https://user-images.githubusercontent.com/33802186/59330652-9df61500-8d24-11e9-9ca7-450cfa616e50.jpeg)
![7835EC56-C2BA-45B0-8B4C-FE01823A5700](https://user-images.githubusercontent.com/33802186/59330669-aa7a6d80-8d24-11e9-866f-31486c165415.jpeg)
![FD0E374B-AA40-467E-B719-7712E77C84CE](https://user-images.githubusercontent.com/33802186/59330681-b5350280-8d24-11e9-8101-9884758eee19.jpeg)
![B29B2294-7039-43B9-9D69-10E23797D414](https://user-images.githubusercontent.com/33802186/59330696-bf570100-8d24-11e9-8604-98bb12041bd1.jpeg)

**Comment by sfyc23** [comment]
已经实现了，等会更新吧。。。

**Comment by sfyc23** [comment]
已加
