### ISSUE TITLE
所有人都自动回复？可以设置某个人自动回复吗

### ISSUE THREAD

**Issue by meiniepan** [sfyc23/EverydayWechat#82]
怎么设置每一小时自动发消息的定时任务？

**Comment by sfyc23** [comment]
这个版本只是回复填写的 girlfriend_infos 里的微信好友。  

设置一小时：

删除
‘’‘
 scheduler.add_job(self.start_today_info, 'cron', hour=self.alarm_hour,
                          minute=self.alarm_minute, misfire_grace_time=GRACE_PERIOD)
’‘’
添加：
```
# 每隔 1 小时发送一条数据用于测试。
 scheduler.add_job(self.start_today_info, 'interval', seconds=60*60)
```

**Comment by meiniepan** [comment]
谢谢啦
