### ISSUE TITLE
运行成功之后，提示下载二维码但一直没有打印登录的二维码

### ISSUE THREAD

**Issue by reflex-spec** [sfyc23/EverydayWechat#84]
![image](https://user-images.githubusercontent.com/51686032/59357489-85eeb780-8d5d-11e9-8fb8-0f941bddd61a.png)

**Comment by sfyc23** [comment]
你看一下 itchat 的文档。https://itchat.readthedocs.io/zh/latest/   

![image](https://user-images.githubusercontent.com/7067207/59361069-dbc65e00-8d63-11e9-8e41-ae9eb42b3dea.png)

这几种方法都试一下。  
我也不知道这是什么问题。
