### ISSUE TITLE
citycode 那个网站打不开 cityid 不知道填什么

### ISSUE THREAD

**Issue by L1cardo** [sfyc23/EverydayWechat#88]
city_code 城市对应 id。 
http://cdn.sojson.com/_city.json

这个网站打不开，希望你能整理一下，然后直接在github里呈现一下，谢谢

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by sfyc23** [comment]
在 https://github.com/sfyc23/EverydayWechat/blob/master/city_dict.py 文件中也可以找到对应的城市 id。

**Comment by L1cardo** [comment]
那只需要改config里面的城市名称就好了吗？还是说city_code里面的city_id也要更改？

**Comment by sfyc23** [comment]
城市名称即可。

**Comment by L1cardo** [comment]
嗯嗯 谢谢啦
