### ISSUE TITLE
weather api网站更换了域名

### ISSUE THREAD

**Issue by cnkenan** [sfyc23/EverydayWechat#9]
每天发送的数据为none，因为天气API更换了域名，需要修改
`weather_url = f'http://t.weather.itboy.net/api/weather/city/{city_code}'`

**Comment by cnkenan** [comment]
https://www.sojson.com/blog/305.html

**Comment by sfyc23** [comment]
我刚测试了一下，http://t.weather.sojson.com/api/weather/city/{city_code} 这个的接口还可以用。

**Comment by cnkenan** [comment]
那我也不知道嘞，本来好几天运行只显示none，换了这个接口才好了，感谢大神
