### ISSUE TITLE
请问下userid怎么获取

### ISSUE THREAD

**Issue by ChinaZeng** [sfyc23/EverydayWechat#90]
我注册了图灵机器人，但是没有userid这个东西。请问在哪获取这个玩意

**Comment by sfyc23** [comment]
![image](https://user-images.githubusercontent.com/7067207/59402962-4367c200-8dd3-11e9-856b-2f78a32435fd.png)
个人中心的右上角数字

**Comment by sfyc23** [comment]
这个得申请个人实现验证才能用。
