### ISSUE TITLE
这是深情还是舔狗的最高境界???

### ISSUE THREAD

**Issue by Yangdaidai** [sfyc23/EverydayWechat#99]
这是深情还是舔狗的最高境界???

**Comment by shinux** [comment]
应该算是最懒惰最不走心最没有灵魂的方式了，太 low 了我是不信有女孩能接受并且长期接受这种消息。

**Comment by sfyc23** [comment]
老哥，我不觉得这东西能被误导什么啊……

**Comment by Dafrok** [comment]
好歹训练个 AI 模仿你的口吻和话术我觉得也算走心了

**Comment by sfyc23** [comment]
嗯，这个项目关注者大部分都是小白用户，安装 pip 还得搞半天的那种。训练集 Github 也有大把的啊。
